Fixing compilation.
When one first clears the repository:

	git clean -dfx

and then tries to compile this coq-contrib:

	coq_makefile -f Make -o Makefile && make

then the compilation always failed with the following error message:

	make -C extraction all
	make[1]: Entering directory '/home/me/git/coq-contribs/stalmarck/extraction'
	Makefile:58: stal.ml.d: No such file or directory
	Makefile:58: lexer.ml.d: No such file or directory
	Makefile:58: parser.ml.d: No such file or directory
	Makefile:58: main.ml.d: No such file or directory
	ocamllex lexer.mll
	22 states, 358 transitions, table size 1564 bytes
	ocamlyacc parser.mly
	ocamldep main.ml > main.ml.d
	ocamldep parser.ml > parser.ml.d
	ocamldep lexer.ml > lexer.ml.d
	cp ../run.ml stal.ml
	ocamldep stal.ml > stal.ml.d
	ocamlopt -c stal.ml
	cp ../run.mli stal.mli
	ocamlopt -c stal.mli
	ocamlopt -c parser.mli
	ocamlopt -c parser.ml
	ocamlopt -c lexer.ml
	ocamlopt -c main.ml
	ocamlopt -cclib -lunix -o stalmarck unix.cmxa stal.cmx lexer.cmx parser.cmx main.cmx
	File "_none_", line 1:
	Error: Files lexer.cmx and stal.cmx
	       make inconsistent assumptions over interface Stal
	Makefile:22: recipe for target 'stalmarck' failed
	make[1]: *** [stalmarck] Error 2
	make[1]: Leaving directory '/home/me/git/coq-contribs/stalmarck/extraction'
	Makefile:275: recipe for target 'extraction/stalmarck' failed
	make: *** [extraction/stalmarck] Error 2

Oddly enough, when one tries this:

	make -C extraction clean all

then the compilation succeeded.

As indicated by these error messages:

	Makefile:58: stal.ml.d: No such file or directory
	Makefile:58: lexer.ml.d: No such file or directory
	Makefile:58: parser.ml.d: No such file or directory
	Makefile:58: main.ml.d: No such file or directory

make tries to use some files at the point where they are not created yet.

Also, originally, the dependencies files were regenerated twice.
The first version was wrong (leading to the above error)
and just the second version (after second running of make) was correct.

This commit fixes that problem:
- dependencies were added to the repository
- the "make" does not regenerate the dependencies whenever it is run
- the user can explicitely regenerate the dependencies whenever it deems necessary
  (there is ".depend" target for that)